export const STICKER_CATEGORIES = [
  {
    id: "destacados",
    label: "Destacados",
    items: [
      ["⭐", "Estrella"],
      ["🔥", "Fuego"],
      ["✨", "Brillos"],
      ["💥", "Impacto"],
      ["❤️", "Corazón"],
      ["🎉", "Fiesta"],
      ["🚀", "Cohete"],
      ["🏆", "Trofeo"],
      ["✅", "Aprobado"],
      ["💎", "Premium"],
      ["📣", "Anuncio"],
      ["🔔", "Campana"],
    ],
  },
  {
    id: "ventas",
    label: "Ventas",
    items: [
      ["🛒", "Carrito"],
      ["🛍️", "Compras"],
      ["💰", "Dinero"],
      ["💳", "Tarjeta"],
      ["🏷️", "Etiqueta"],
      ["🎁", "Regalo"],
      ["📦", "Paquete"],
      ["📈", "Crecimiento"],
      ["💯", "Cien"],
      ["⚡", "Rápido"],
      ["⏰", "Tiempo"],
      ["📍", "Ubicación"],
    ],
  },
  {
    id: "flechas",
    label: "Flechas",
    items: [
      ["➡️", "Derecha"],
      ["⬅️", "Izquierda"],
      ["⬆️", "Arriba"],
      ["⬇️", "Abajo"],
      ["↗️", "Diagonal"],
      ["🔜", "Próximamente"],
      ["👉", "Señalar"],
      ["👇", "Señalar abajo"],
      ["👆", "Señalar arriba"],
      ["🔄", "Girar"],
      ["➕", "Más"],
      ["❗", "Importante"],
    ],
  },
  {
    id: "emociones",
    label: "Emojis",
    items: [
      ["😀", "Feliz"],
      ["😍", "Enamorado"],
      ["😎", "Genial"],
      ["🤩", "Sorprendido"],
      ["😂", "Risa"],
      ["🥳", "Celebración"],
      ["🤔", "Pensando"],
      ["😱", "Sorpresa"],
      ["👏", "Aplauso"],
      ["🙌", "Celebrar"],
      ["👍", "Me gusta"],
      ["💪", "Fuerza"],
    ],
  },
  {
    id: "comercio",
    label: "Comercio",
    items: [
      ["🏪", "Comercio"],
      ["🏬", "Tienda"],
      ["🍔", "Comida"],
      ["☕", "Café"],
      ["👗", "Ropa"],
      ["💇", "Belleza"],
      ["🔧", "Servicio"],
      ["🚗", "Automotor"],
      ["🏠", "Hogar"],
      ["📱", "Tecnología"],
      ["🐶", "Mascotas"],
      ["🩺", "Salud"],
    ],
  },
];
