export const FONT_OPTIONS = [
  "Arial",
  "Arial Black",
  "Verdana",
  "Tahoma",
  "Trebuchet MS",
  "Georgia",
  "Times New Roman",
  "Courier New",
  "Impact",
];

export const TEXT_PRESETS = [
  {
    id: "minimal",
    label: "Minimal",
    changes: {
      fontFamily: "Montserrat",
      fontWeight: 700,
      color: "#ffffff",
      strokeEnabled: false,
      shadowEnabled: true,
      backgroundEnabled: false,
      letterSpacing: 0,
      lineHeight: 1.08,
    },
  },
  {
    id: "premium",
    label: "Premium",
    changes: {
      fontFamily: "Georgia",
      fontWeight: 700,
      color: "#f8e7b0",
      strokeEnabled: false,
      shadowEnabled: true,
      backgroundEnabled: true,
      backgroundColor: "#111111",
      backgroundOpacity: 0.72,
      letterSpacing: 2,
      lineHeight: 1.1,
    },
  },
  {
    id: "oferta",
    label: "Oferta",
    changes: {
      fontFamily: "Impact",
      fontWeight: 900,
      color: "#fff200",
      strokeEnabled: true,
      strokeColor: "#111111",
      strokeWidth: 4,
      shadowEnabled: true,
      backgroundEnabled: true,
      backgroundColor: "#e11d48",
      backgroundOpacity: 0.92,
      letterSpacing: 1,
      lineHeight: 1,
    },
  },
  {
    id: "subtitulo",
    label: "Subtítulo",
    changes: {
      fontFamily: "Montserrat",
      fontWeight: 800,
      color: "#ffffff",
      strokeEnabled: false,
      shadowEnabled: true,
      backgroundEnabled: true,
      backgroundColor: "#000000",
      backgroundOpacity: 0.72,
      letterSpacing: 0,
      lineHeight: 1.1,
    },
  },
  {
    id: "neon",
    label: "Neón",
    changes: {
      fontFamily: "Poppins",
      fontWeight: 900,
      color: "#67e8f9",
      strokeEnabled: true,
      strokeColor: "#0e7490",
      strokeWidth: 2,
      shadowEnabled: true,
      shadowColor: "#22d3ee",
      shadowBlur: 26,
      backgroundEnabled: false,
      letterSpacing: 1,
      lineHeight: 1.05,
    },
  },
  {
    id: "urgente",
    label: "Urgente",
    changes: {
      fontFamily: "Arial Black",
      fontWeight: 900,
      color: "#ffffff",
      strokeEnabled: false,
      shadowEnabled: true,
      backgroundEnabled: true,
      backgroundColor: "#dc2626",
      backgroundOpacity: 0.96,
      letterSpacing: 1,
      lineHeight: 1,
    },
  },
];
