import {
  SCENE_TYPES,
  buildDirectorContext,
  createDirectedScene,
  createEndScene,
  cycleMedia,
  distributeDurations,
  DIRECTOR_MODES,
} from "./directorBase";

export function buildTusComerciosDirectorPlan(input = {}) {
  const context = buildDirectorContext({
    ...input,
    mode: DIRECTOR_MODES.ADMIN,
    style: "tuscomercios",
  });

  const scenes = [
    createDirectedScene({
      type: SCENE_TYPES.HOOK,
      media: cycleMedia(context.media, 0),
      title: context.title || "ENCONTRÁ TODO CERCA TUYO",
      subtitle: context.subtitle || "Comercios, servicios y profesionales en un solo lugar.",
      duration: 2.5,
      camera: "pushIn",
      transition: "zoom",
      model: "commercial",
      textPosition: "center",
      textAlign: "left",
      overlayOpacity: 0.5,
      titleSize: 126,
      subtitleSize: 40,
      cameraIntensity: 1.15,
      cameraEasing: "dynamic",
      seed: 21,
    }),
    createDirectedScene({
      type: SCENE_TYPES.PRODUCT,
      media: cycleMedia(context.media, 1),
      title: "BUSCÁ POR RUBRO Y CIUDAD",
      subtitle: "Encontrá opciones reales y contactá directamente.",
      duration: 3,
      camera: "panRight",
      transition: "slideLeft",
      model: "commercial",
      textPosition: "bottom",
      textAlign: "left",
      overlayOpacity: 0.42,
      cameraIntensity: 0.95,
      cameraEasing: "smooth",
      seed: 22,
    }),
    createDirectedScene({
      type: SCENE_TYPES.SOCIAL,
      media: cycleMedia(context.media, 2),
      title: "DESCUBRÍ NUEVOS COMERCIOS",
      subtitle: "Conocé propuestas, promociones y servicios de tu zona.",
      duration: 3,
      camera: "kenBurns",
      transition: "blur",
      model: "cinematic",
      textPosition: "bottom",
      textAlign: "left",
      overlayOpacity: 0.44,
      cameraIntensity: 0.85,
      cameraEasing: "cinematic",
      seed: 23,
    }),
    createDirectedScene({
      type: SCENE_TYPES.PROMOTION,
      media: cycleMedia(context.media, 3),
      title: "TU COMERCIO TAMBIÉN PUEDE ESTAR",
      subtitle: "Mostrá tu negocio y llegá a más personas.",
      duration: 3,
      camera: "diagonalPush",
      transition: "flash",
      model: "commercial",
      textPosition: "center",
      textAlign: "center",
      overlayOpacity: 0.58,
      titleSize: 116,
      subtitleSize: 38,
      cameraIntensity: 1.05,
      cameraEasing: "dynamic",
      seed: 24,
    }),
    createDirectedScene({
      type: SCENE_TYPES.CTA,
      media: cycleMedia(context.media, 4),
      title: "TUSCOMERCIOS.COM.AR",
      subtitle: "Buscá, descubrí y conectá.",
      duration: 2.5,
      camera: "floating",
      transition: "fade",
      model: "minimal",
      textPosition: "center",
      textAlign: "center",
      overlayOpacity: 0.62,
      titleSize: 96,
      subtitleSize: 34,
      cameraIntensity: 0.65,
      cameraEasing: "cinematic",
      seed: 25,
    }),
    createEndScene({
      context: { ...context, businessName: "TusComercios", whatsapp: "" },
      model: "minimal",
      title: "TUSCOMERCIOS",
      subtitle: "La plataforma de comercios de Argentina",
      seed: 26,
    }),
  ];

  return {
    id: "tuscomercios-director",
    name: "Director TusComercios",
    mode: DIRECTOR_MODES.ADMIN,
    category: "platform",
    model: "commercial",
    targetDuration: context.targetDuration,
    scenes: distributeDurations(scenes, context.targetDuration),
  };
}
