export const OFFICIAL_CAMPAIGNS = [
  {
    id: "discover",
    label: "Descubrí TusComercios",
    description: "Promociona buscador, categorías, ciudades y vidrieras.",
    duration: 20,
    steps: [
      "Abrí la página principal.",
      "Mostrá el buscador.",
      "Escribí una ciudad o categoría.",
      "Entrá a una vidriera.",
      "Mostrá el botón de WhatsApp.",
    ],
    captions: [
      "¿Todavía no conocés TusComercios?",
      "Buscá comercios por ciudad y categoría",
      "Encontrá productos, servicios y profesionales",
      "Conocé cada negocio antes de contactarlo",
      "TusComercios. Todo más cerca.",
    ],
  },
  {
    id: "studio",
    label: "Conocé TusComercios Studio",
    description: "Muestra Brand Kit, editor de imágenes y generador de Reels.",
    duration: 25,
    steps: [
      "Entrá a Studio.",
      "Mostrá el Brand Kit.",
      "Abrí el editor de imágenes.",
      "Mové un texto o una foto.",
      "Mostrá el generador de Reels.",
      "Cerrá mostrando el resultado final.",
    ],
    captions: [
      "Tu negocio también puede crear contenido profesional",
      "Guardá colores, logos y estilo en tu Brand Kit",
      "Diseñá publicaciones sin saber diseño",
      "Editá fotos, textos, stickers y formatos",
      "Creá Reels automáticos con fotos y videos",
      "TusComercios Studio. Marketing más simple.",
    ],
  },
  {
    id: "premium",
    label: "Beneficios de los planes pagos",
    description: "Explica visibilidad, estadísticas, Studio y herramientas.",
    duration: 20,
    steps: [
      "Mostrá una vidriera destacada.",
      "Mostrá estadísticas.",
      "Mostrá Studio.",
      "Mostrá creación de imágenes y Reels.",
      "Cerrá con una invitación a mejorar el plan.",
    ],
    captions: [
      "Tu negocio merece más visibilidad",
      "Conocé cuántas personas ven tu vidriera",
      "Creá contenido profesional desde Studio",
      "Publicaciones y Reels en pocos minutos",
      "Mejorá tu plan y conseguí más oportunidades",
    ],
  },
  {
    id: "publish",
    label: "Publicá tu comercio",
    description: "Campaña para conseguir nuevos comercios.",
    duration: 20,
    steps: [
      "Mostrá el registro.",
      "Completá datos principales.",
      "Subí un logo o una foto.",
      "Mostrá la vidriera publicada.",
      "Cerrá con el llamado a sumarse.",
    ],
    captions: [
      "¿Tenés un comercio o prestás un servicio?",
      "Creá tu perfil en pocos pasos",
      "Mostrá fotos, ubicación y formas de contacto",
      "Tu vidriera queda disponible para nuevos clientes",
      "Sumate a TusComercios",
    ],
  },
  {
    id: "municipal",
    label: "Portal Municipal",
    description: "Presenta noticias, eventos, turismo y áreas municipales.",
    duration: 20,
    steps: [
      "Entrá al portal municipal.",
      "Mostrá noticias y avisos.",
      "Mostrá eventos o turismo.",
      "Mostrá áreas municipales.",
      "Cerrá con el nombre de la localidad.",
    ],
    captions: [
      "La información de tu localidad en un solo lugar",
      "Noticias y avisos importantes",
      "Eventos, turismo y actividades",
      "Acceso directo a las áreas municipales",
      "Municipios conectados con su comunidad",
    ],
  },
  {
    id: "feature",
    label: "Anunciar una nueva función",
    description: "Plantilla adaptable para Historias, comentarios, QR y novedades.",
    duration: 15,
    steps: [
      "Mostrá la función nueva.",
      "Hacé una demostración corta.",
      "Mostrá el beneficio.",
      "Cerrá invitando a probarla.",
    ],
    captions: [
      "Nueva función en TusComercios",
      "Más simple, rápida y útil",
      "Pensada para comercios y clientes",
      "Probala ahora",
    ],
  },
];

export const SUBTITLE_PRESETS = [
  {
    id: "premium",
    label: "Premium",
    subtitleStyle: "word-reveal",
    titleAnimation: "rise",
    subtitleAnimation: "word-reveal",
  },
  {
    id: "commercial",
    label: "Comercial",
    subtitleStyle: "highlight",
    titleAnimation: "zoom",
    subtitleAnimation: "highlight",
  },
  {
    id: "minimal",
    label: "Minimal",
    subtitleStyle: "fade",
    titleAnimation: "fade",
    subtitleAnimation: "fade",
  },
];
