create table if not exists public.mentor_daily_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check (entity_type in ('business', 'workspace')),
  entity_id uuid not null,
  usage_date date not null,
  responses_used integer not null default 0 check (responses_used >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entity_type, entity_id, usage_date)
);

create table if not exists public.mentor_usage_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check (entity_type in ('business', 'workspace')),
  entity_id uuid not null,
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists mentor_usage_log_user_created_idx
  on public.mentor_usage_log (user_id, created_at desc);

alter table public.mentor_daily_usage enable row level security;
alter table public.mentor_usage_log enable row level security;

-- El navegador no modifica estos datos directamente.
-- La Edge Function usa la service role y valida al usuario autenticado.
