-- TusComercios Administración V6.
-- Compras, transferencias, gastos recurrentes, configuración y documentos vinculados.

create or replace function public.can_manage_administration(p_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_tc_admin()
    or exists (
      select 1
      from public.businesses b
      join public.administration_subscriptions s
        on s.business_id = b.id and s.status = 'authorized'
      where b.id = p_business_id and b.user_id = auth.uid()
    );
$$;

revoke all on function public.can_manage_administration(uuid) from public;
grant execute on function public.can_manage_administration(uuid) to authenticated;

create table if not exists public.admin_business_settings (
  business_id uuid primary key references public.businesses(id) on delete cascade,
  display_name text not null default 'TusComercios',
  whatsapp text,
  email text,
  address text,
  tax_id text,
  logo_url text,
  watermark_text text not null default 'TusComercios!',
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_purchases (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id uuid not null references public.admin_branches(id) on delete restrict,
  supplier_id uuid references public.admin_suppliers(id) on delete set null,
  purchase_number bigint generated by default as identity,
  invoice_reference text,
  payment_method text not null default 'cash',
  total numeric(14,2) not null default 0,
  paid_amount numeric(14,2) not null default 0,
  balance_due numeric(14,2) not null default 0,
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_purchase_items (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null references public.admin_purchases(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  product_id uuid not null references public.admin_products(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  unit_cost numeric(14,2) not null check (unit_cost >= 0),
  subtotal numeric(14,2) not null default 0
);

create table if not exists public.admin_stock_transfers (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  from_branch_id uuid not null references public.admin_branches(id) on delete restrict,
  to_branch_id uuid not null references public.admin_branches(id) on delete restrict,
  transfer_number bigint generated by default as identity,
  notes text,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  check (from_branch_id <> to_branch_id)
);

create table if not exists public.admin_stock_transfer_items (
  id uuid primary key default gen_random_uuid(),
  transfer_id uuid not null references public.admin_stock_transfers(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  product_id uuid not null references public.admin_products(id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0)
);

create table if not exists public.admin_recurring_expenses (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  branch_id uuid references public.admin_branches(id) on delete cascade,
  description text not null,
  category text not null default 'Gasto fijo',
  amount numeric(14,2) not null check (amount > 0),
  frequency text not null default 'monthly'
    check (frequency in ('weekly', 'monthly', 'yearly')),
  next_due_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.admin_employees
  add column if not exists email text,
  add column if not exists permissions jsonb not null default
    '{"sales":true,"cash":false,"stock":false,"documents":false,"reports":false}'::jsonb,
  add column if not exists updated_at timestamptz not null default now();

alter table public.admin_documents
  add column if not exists source_document_id uuid references public.admin_documents(id) on delete set null,
  add column if not exists source_sale_id uuid references public.admin_sales(id) on delete set null;

create index if not exists admin_purchases_date_idx
  on public.admin_purchases (business_id, created_at desc);
create index if not exists admin_transfers_date_idx
  on public.admin_stock_transfers (business_id, created_at desc);
create index if not exists admin_recurring_due_idx
  on public.admin_recurring_expenses (business_id, next_due_date);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'admin_business_settings', 'admin_purchases', 'admin_purchase_items',
    'admin_stock_transfers', 'admin_stock_transfer_items',
    'admin_recurring_expenses'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists tc_admin_owner on public.%I', table_name);
    execute format(
      'create policy tc_admin_owner on public.%I for all to authenticated using (public.can_manage_administration(business_id)) with check (public.can_manage_administration(business_id))',
      table_name
    );
  end loop;
end $$;

grant select, insert, update, delete on
  public.admin_business_settings, public.admin_purchases,
  public.admin_purchase_items, public.admin_stock_transfers,
  public.admin_stock_transfer_items, public.admin_recurring_expenses
to authenticated;

create or replace function public.create_administration_purchase(
  p_business_id uuid,
  p_branch_id uuid,
  p_supplier_id uuid,
  p_payment_method text,
  p_paid_amount numeric,
  p_invoice_reference text,
  p_notes text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_purchase_id uuid;
  v_cash_session_id uuid;
  v_item jsonb;
  v_product public.admin_products%rowtype;
  v_quantity numeric(14,3);
  v_cost numeric(14,2);
  v_total numeric(14,2) := 0;
  v_paid numeric(14,2);
  v_balance numeric(14,2);
begin
  if not public.can_manage_administration(p_business_id) then
    raise exception 'No tenés permiso para administrar este negocio';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Agregá al menos un producto';
  end if;
  if not exists (
    select 1 from public.admin_branches
    where id = p_branch_id and business_id = p_business_id and active
  ) then
    raise exception 'La sucursal no es válida';
  end if;
  if p_supplier_id is not null and not exists (
    select 1 from public.admin_suppliers
    where id = p_supplier_id and business_id = p_business_id and active
  ) then
    raise exception 'El proveedor no es válido';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := coalesce((v_item->>'quantity')::numeric, 0);
    v_cost := coalesce((v_item->>'unit_cost')::numeric, 0);
    if v_quantity <= 0 or v_cost < 0 then
      raise exception 'Revisá cantidades y costos';
    end if;
    select * into v_product from public.admin_products
      where id = (v_item->>'product_id')::uuid
        and business_id = p_business_id and active;
    if not found then raise exception 'Uno de los productos no es válido'; end if;
    v_total := v_total + v_quantity * v_cost;
  end loop;

  v_paid := least(greatest(coalesce(p_paid_amount, 0), 0), v_total);
  v_balance := v_total - v_paid;
  if v_paid > 0 then
    select id into v_cash_session_id from public.admin_cash_sessions
      where business_id = p_business_id and branch_id = p_branch_id
        and status = 'open' limit 1;
    if v_cash_session_id is null then
      raise exception 'Abrí la caja antes de registrar un pago de compra';
    end if;
  end if;
  if v_balance > 0 and p_supplier_id is null then
    raise exception 'Elegí un proveedor para dejar saldo pendiente';
  end if;

  insert into public.admin_purchases (
    business_id, branch_id, supplier_id, invoice_reference,
    payment_method, total, paid_amount, balance_due, notes
  ) values (
    p_business_id, p_branch_id, p_supplier_id,
    nullif(trim(p_invoice_reference), ''), p_payment_method,
    v_total, v_paid, v_balance, nullif(trim(p_notes), '')
  ) returning id into v_purchase_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item->>'quantity')::numeric;
    v_cost := (v_item->>'unit_cost')::numeric;
    select * into v_product from public.admin_products
      where id = (v_item->>'product_id')::uuid;

    insert into public.admin_purchase_items (
      purchase_id, business_id, product_id, quantity, unit_cost, subtotal
    ) values (
      v_purchase_id, p_business_id, v_product.id, v_quantity,
      v_cost, v_quantity * v_cost
    );
    insert into public.admin_branch_stock (
      business_id, branch_id, product_id, quantity
    ) values (
      p_business_id, p_branch_id, v_product.id, v_quantity
    ) on conflict (branch_id, product_id)
      do update set quantity = public.admin_branch_stock.quantity + excluded.quantity,
        updated_at = now();
    update public.admin_products set cost = v_cost, updated_at = now()
      where id = v_product.id;
    insert into public.admin_inventory_movements (
      business_id, branch_id, product_id, movement_type, quantity,
      unit_cost, reference_type, reference_id, notes
    ) values (
      p_business_id, p_branch_id, v_product.id, 'purchase', v_quantity,
      v_cost, 'purchase', v_purchase_id, 'Compra a proveedor'
    );
  end loop;

  if v_paid > 0 then
    insert into public.admin_cash_movements (
      business_id, branch_id, cash_session_id, movement_type,
      category, description, amount, payment_method
    ) values (
      p_business_id, p_branch_id, v_cash_session_id, 'expense',
      'Compra', 'Compra de mercadería', v_paid, p_payment_method
    );
  end if;
  if v_balance > 0 then
    insert into public.admin_account_movements (
      business_id, supplier_id, movement_type, amount,
      description, reference_type, reference_id
    ) values (
      p_business_id, p_supplier_id, 'debit', v_balance,
      'Compra con saldo pendiente', 'purchase', v_purchase_id
    );
  end if;
  insert into public.admin_audit_log (
    business_id, action, entity_type, entity_id, details
  ) values (
    p_business_id, 'create', 'purchase', v_purchase_id::text,
    jsonb_build_object('total', v_total, 'paid', v_paid)
  );
  return v_purchase_id;
end;
$$;

create or replace function public.create_administration_transfer(
  p_business_id uuid,
  p_from_branch_id uuid,
  p_to_branch_id uuid,
  p_notes text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_transfer_id uuid;
  v_item jsonb;
  v_product_id uuid;
  v_quantity numeric(14,3);
  v_available numeric(14,3);
  v_cost numeric(14,2);
begin
  if not public.can_manage_administration(p_business_id) then
    raise exception 'No tenés permiso para administrar este negocio';
  end if;
  if p_from_branch_id = p_to_branch_id then
    raise exception 'Elegí dos sucursales diferentes';
  end if;
  if (select count(*) from public.admin_branches
      where business_id = p_business_id and active
        and id in (p_from_branch_id, p_to_branch_id)) <> 2 then
    raise exception 'Una de las sucursales no es válida';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Agregá productos a la transferencia';
  end if;
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_item->>'product_id')::uuid;
    v_quantity := coalesce((v_item->>'quantity')::numeric, 0);
    select quantity into v_available from public.admin_branch_stock
      where branch_id = p_from_branch_id and product_id = v_product_id
      for update;
    if v_quantity <= 0 or coalesce(v_available, 0) < v_quantity then
      raise exception 'Stock insuficiente para realizar la transferencia';
    end if;
  end loop;

  insert into public.admin_stock_transfers (
    business_id, from_branch_id, to_branch_id, notes
  ) values (
    p_business_id, p_from_branch_id, p_to_branch_id, nullif(trim(p_notes), '')
  ) returning id into v_transfer_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_item->>'product_id')::uuid;
    v_quantity := (v_item->>'quantity')::numeric;
    select cost into v_cost from public.admin_products where id = v_product_id;
    insert into public.admin_stock_transfer_items (
      transfer_id, business_id, product_id, quantity
    ) values (v_transfer_id, p_business_id, v_product_id, v_quantity);
    update public.admin_branch_stock
      set quantity = quantity - v_quantity, updated_at = now()
      where branch_id = p_from_branch_id and product_id = v_product_id;
    insert into public.admin_branch_stock (
      business_id, branch_id, product_id, quantity
    ) values (p_business_id, p_to_branch_id, v_product_id, v_quantity)
    on conflict (branch_id, product_id)
      do update set quantity = public.admin_branch_stock.quantity + excluded.quantity,
        updated_at = now();
    insert into public.admin_inventory_movements (
      business_id, branch_id, product_id, movement_type, quantity,
      unit_cost, reference_type, reference_id, notes
    ) values
      (p_business_id, p_from_branch_id, v_product_id, 'transfer_out',
       -v_quantity, v_cost, 'transfer', v_transfer_id, 'Transferencia enviada'),
      (p_business_id, p_to_branch_id, v_product_id, 'transfer_in',
       v_quantity, v_cost, 'transfer', v_transfer_id, 'Transferencia recibida');
  end loop;
  insert into public.admin_audit_log (
    business_id, action, entity_type, entity_id, details
  ) values (
    p_business_id, 'create', 'stock_transfer', v_transfer_id::text,
    jsonb_build_object('from', p_from_branch_id, 'to', p_to_branch_id)
  );
  return v_transfer_id;
end;
$$;

create or replace function public.convert_administration_quote_to_sale(
  p_document_id uuid,
  p_payment_method text,
  p_paid_amount numeric
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_document public.admin_documents%rowtype;
  v_items jsonb;
  v_sale_id uuid;
begin
  select * into v_document from public.admin_documents
    where id = p_document_id and document_type = 'quote' and status = 'issued';
  if not found or not public.can_manage_administration(v_document.business_id) then
    raise exception 'El presupuesto no es válido o ya fue utilizado';
  end if;
  select jsonb_agg(jsonb_build_object(
    'product_id', product_id, 'quantity', quantity
  )) into v_items
  from public.admin_document_items
  where document_id = p_document_id and product_id is not null;
  if v_items is null then
    raise exception 'El presupuesto necesita productos del inventario para convertirse';
  end if;
  v_sale_id := public.complete_administration_credit_sale(
    v_document.business_id, v_document.branch_id, p_payment_method,
    v_document.customer_id, p_paid_amount, v_items
  );
  update public.admin_documents
    set status = 'accepted', source_sale_id = v_sale_id
    where id = p_document_id;
  return v_sale_id;
end;
$$;

create or replace function public.create_delivery_note_from_sale(p_sale_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.admin_sales%rowtype;
  v_document_id uuid;
begin
  select * into v_sale from public.admin_sales where id = p_sale_id;
  if not found or not public.can_manage_administration(v_sale.business_id) then
    raise exception 'La venta no es válida';
  end if;
  insert into public.admin_documents (
    business_id, branch_id, customer_id, document_type,
    status, subtotal, total, notes, source_sale_id
  ) values (
    v_sale.business_id, v_sale.branch_id, v_sale.customer_id,
    'delivery_note', 'issued', v_sale.subtotal, v_sale.total,
    'Remito generado desde la venta N.º ' || v_sale.sale_number, v_sale.id
  ) returning id into v_document_id;
  insert into public.admin_document_items (
    document_id, business_id, product_id, description,
    quantity, unit_price, subtotal
  )
  select v_document_id, business_id, product_id, description,
    quantity, unit_price, subtotal
  from public.admin_sale_items where sale_id = p_sale_id;
  return v_document_id;
end;
$$;

revoke all on function public.create_administration_purchase(
  uuid, uuid, uuid, text, numeric, text, text, jsonb
) from public;
grant execute on function public.create_administration_purchase(
  uuid, uuid, uuid, text, numeric, text, text, jsonb
) to authenticated;
revoke all on function public.create_administration_transfer(
  uuid, uuid, uuid, text, jsonb
) from public;
grant execute on function public.create_administration_transfer(
  uuid, uuid, uuid, text, jsonb
) to authenticated;
revoke all on function public.convert_administration_quote_to_sale(uuid, text, numeric)
  from public;
grant execute on function public.convert_administration_quote_to_sale(uuid, text, numeric)
  to authenticated;
revoke all on function public.create_delivery_note_from_sale(uuid) from public;
grant execute on function public.create_delivery_note_from_sale(uuid) to authenticated;
