-- Carruseles y análisis creativos validados en servidor.
-- Estándar: 2 carruseles y 1 análisis por editor/día.
-- Premium: 4 carruseles y 2 análisis por editor/día.

create table if not exists public.mentor_director_daily_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entity_type text not null check (entity_type in ('business', 'workspace')),
  entity_id uuid not null,
  editor_type text not null check (editor_type in ('image', 'reel', 'carousel')),
  usage_date date not null,
  analyses_used integer not null default 0 check (analyses_used >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entity_type, entity_id, editor_type, usage_date)
);

alter table public.mentor_director_daily_usage enable row level security;
revoke all on public.mentor_director_daily_usage from anon, authenticated;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.mentor_director_daily_usage'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%editor_type%'
  ) then
    execute (
      select 'alter table public.mentor_director_daily_usage drop constraint ' || quote_ident(conname)
      from pg_constraint
      where conrelid = 'public.mentor_director_daily_usage'::regclass
        and contype = 'c'
        and pg_get_constraintdef(oid) ilike '%editor_type%'
      limit 1
    );
  end if;
end $$;

alter table public.mentor_director_daily_usage
  add constraint mentor_director_editor_type_check
  check (editor_type in ('image', 'reel', 'carousel'));

create or replace function public.claim_studio_usage(
  p_business_id uuid,
  p_content_type text
)
returns table (
  allowed boolean,
  usage_id text,
  used integer,
  daily_limit integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_plan text;
  v_role text;
  v_limit integer;
  v_used integer;
  v_usage_id text;
  v_start timestamptz;
  v_end timestamptz;
begin
  if v_user_id is null then raise exception 'Sesión requerida'; end if;
  if p_content_type not in ('image', 'reel', 'carousel') then
    raise exception 'Tipo de contenido inválido';
  end if;

  select lower(coalesce(p.role, 'user')) into v_role
  from public.profiles p where p.id = v_user_id;

  select lower(coalesce(b.plan, 'free')) into v_plan
  from public.businesses b
  where b.id = p_business_id
    and (b.user_id = v_user_id or v_role = 'admin')
  for update;

  if v_plan is null then raise exception 'No tenés permiso para usar este comercio'; end if;

  if v_role = 'admin' then v_limit := 2147483647;
  elsif v_plan in ('standard', 'estandar') and p_content_type = 'image' then v_limit := 10;
  elsif v_plan in ('standard', 'estandar') and p_content_type = 'reel' then v_limit := 1;
  elsif v_plan in ('standard', 'estandar') and p_content_type = 'carousel' then v_limit := 2;
  elsif v_plan = 'premium' and p_content_type = 'image' then v_limit := 20;
  elsif v_plan = 'premium' and p_content_type = 'reel' then v_limit := 2;
  elsif v_plan = 'premium' and p_content_type = 'carousel' then v_limit := 4;
  else v_limit := 0;
  end if;

  v_start := date_trunc('day', now() at time zone 'America/Argentina/Cordoba')
    at time zone 'America/Argentina/Cordoba';
  v_end := v_start + interval '1 day';

  select count(*)::integer into v_used
  from public.studio_usage s
  where s.user_id = v_user_id
    and s.business_id = p_business_id
    and s.content_type = p_content_type
    and s.created_at >= v_start and s.created_at < v_end;

  if v_used >= v_limit then
    return query select false, null::text, v_used, v_limit;
    return;
  end if;

  insert into public.studio_usage (user_id, business_id, content_type, plan)
  values (v_user_id, p_business_id, p_content_type, v_plan)
  returning id::text into v_usage_id;

  return query select true, v_usage_id, v_used + 1, v_limit;
end;
$$;

revoke all on function public.claim_studio_usage(uuid, text) from public;
grant execute on function public.claim_studio_usage(uuid, text) to authenticated;
