-- Historias de TusComercios: publicación, programación, métricas y denuncias.

create table if not exists public.business_stories (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('image', 'video')),
  media_url text not null,
  thumbnail_url text,
  caption text not null default '',
  cta_type text not null default 'none'
    check (cta_type in ('none', 'whatsapp', 'showcase', 'product')),
  cta_label text,
  cta_url text,
  scheduled_at timestamptz not null default now(),
  published_at timestamptz,
  expires_at timestamptz,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'published', 'expired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_views (
  id bigint generated by default as identity primary key,
  story_id uuid not null references public.business_stories(id) on delete cascade,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique (story_id, visitor_id)
);

create table if not exists public.story_clicks (
  id bigint generated by default as identity primary key,
  story_id uuid not null references public.business_stories(id) on delete cascade,
  business_id uuid not null references public.businesses(id) on delete cascade,
  visitor_id text not null,
  destination text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.story_reports (
  id bigint generated by default as identity primary key,
  story_id uuid not null references public.business_stories(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  visitor_id text,
  reason text not null,
  details text,
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'dismissed', 'removed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);

create index if not exists business_stories_active_idx
  on public.business_stories (status, scheduled_at, expires_at);
create index if not exists business_stories_business_idx
  on public.business_stories (business_id, scheduled_at desc);
create index if not exists story_reports_pending_idx
  on public.story_reports (status, created_at desc);

alter table public.business_stories enable row level security;
alter table public.story_views enable row level security;
alter table public.story_clicks enable row level security;
alter table public.story_reports enable row level security;

drop policy if exists "stories_public_read" on public.business_stories;
create policy "stories_public_read"
  on public.business_stories for select
  to anon, authenticated
  using (
    (
      status in ('scheduled', 'published')
      and scheduled_at <= now()
      and coalesce(expires_at, scheduled_at + interval '24 hours') > now()
    )
    or user_id = auth.uid()
    or public.is_tc_admin()
  );

drop policy if exists "stories_owner_delete" on public.business_stories;
create policy "stories_owner_delete"
  on public.business_stories for delete
  to authenticated
  using (user_id = auth.uid() or public.is_tc_admin());

drop policy if exists "story_views_public_insert" on public.story_views;
create policy "story_views_public_insert"
  on public.story_views for insert
  to anon, authenticated
  with check (length(visitor_id) between 8 and 100);

drop policy if exists "story_views_owner_read" on public.story_views;
create policy "story_views_owner_read"
  on public.story_views for select
  to authenticated
  using (
    exists (
      select 1 from public.business_stories s
      where s.id = story_id
        and (s.user_id = auth.uid() or public.is_tc_admin())
    )
  );

drop policy if exists "story_clicks_public_insert" on public.story_clicks;
create policy "story_clicks_public_insert"
  on public.story_clicks for insert
  to anon, authenticated
  with check (length(visitor_id) between 8 and 100);

drop policy if exists "story_clicks_owner_read" on public.story_clicks;
create policy "story_clicks_owner_read"
  on public.story_clicks for select
  to authenticated
  using (
    exists (
      select 1 from public.businesses b
      where b.id = business_id
        and (b.user_id = auth.uid() or public.is_tc_admin())
    )
  );

drop policy if exists "story_reports_public_insert" on public.story_reports;
create policy "story_reports_public_insert"
  on public.story_reports for insert
  to anon, authenticated
  with check (
    length(reason) between 3 and 100
    and (reporter_id is null or reporter_id = auth.uid())
  );

drop policy if exists "story_reports_admin_read" on public.story_reports;
create policy "story_reports_admin_read"
  on public.story_reports for select
  to authenticated
  using (public.is_tc_admin());

drop policy if exists "story_reports_admin_update" on public.story_reports;
create policy "story_reports_admin_update"
  on public.story_reports for update
  to authenticated
  using (public.is_tc_admin())
  with check (public.is_tc_admin());

revoke insert, update on public.business_stories from anon, authenticated;
grant select, delete on public.business_stories to anon, authenticated;
grant insert on public.story_views, public.story_clicks, public.story_reports
  to anon, authenticated;
grant select on public.story_views, public.story_clicks to authenticated;
grant select, update on public.story_reports to authenticated;

create or replace function public.create_business_story(
  p_business_id uuid,
  p_media_type text,
  p_media_url text,
  p_thumbnail_url text,
  p_caption text,
  p_cta_type text,
  p_cta_label text,
  p_cta_url text,
  p_scheduled_at timestamptz
)
returns public.business_stories
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_plan text;
  v_role text;
  v_limit integer;
  v_used integer;
  v_scheduled timestamptz := greatest(coalesce(p_scheduled_at, now()), now());
  v_story public.business_stories;
  v_day_start timestamptz;
  v_day_end timestamptz;
begin
  if v_user_id is null then raise exception 'Sesión requerida'; end if;
  if p_media_type not in ('image', 'video') then raise exception 'Contenido inválido'; end if;
  if coalesce(length(trim(p_media_url)), 0) = 0 then raise exception 'Archivo requerido'; end if;
  if p_cta_type not in ('none', 'whatsapp', 'showcase', 'product') then
    raise exception 'Acción inválida';
  end if;

  select lower(coalesce(p.role, 'user')) into v_role
  from public.profiles p where p.id = v_user_id;

  select lower(coalesce(b.plan, 'free')) into v_plan
  from public.businesses b
  where b.id = p_business_id
    and (b.user_id = v_user_id or v_role = 'admin');

  if v_plan is null then raise exception 'No tenés permiso para este comercio'; end if;
  if v_role = 'admin' then v_limit := 2147483647;
  elsif v_plan in ('standard', 'estandar') then v_limit := 5;
  elsif v_plan = 'premium' then v_limit := 10;
  else v_limit := 0;
  end if;

  v_day_start := date_trunc(
    'day',
    v_scheduled at time zone 'America/Argentina/Cordoba'
  ) at time zone 'America/Argentina/Cordoba';
  v_day_end := v_day_start + interval '1 day';

  perform pg_advisory_xact_lock(
    hashtextextended(p_business_id::text || v_day_start::text, 0)
  );

  select count(*)::integer into v_used
  from public.business_stories s
  where s.business_id = p_business_id
    and s.scheduled_at >= v_day_start
    and s.scheduled_at < v_day_end
    and s.status <> 'expired';

  if v_used >= v_limit then
    raise exception 'Alcanzaste el límite de % historias para ese día', v_limit;
  end if;

  insert into public.business_stories (
    business_id, user_id, media_type, media_url, thumbnail_url,
    caption, cta_type, cta_label, cta_url, scheduled_at,
    published_at, expires_at, status
  ) values (
    p_business_id, v_user_id, p_media_type, p_media_url, p_thumbnail_url,
    left(coalesce(p_caption, ''), 500), p_cta_type,
    left(coalesce(p_cta_label, ''), 60), p_cta_url, v_scheduled,
    case when v_scheduled <= now() then now() else null end,
    v_scheduled + interval '24 hours',
    case when v_scheduled <= now() then 'published' else 'scheduled' end
  )
  returning * into v_story;

  return v_story;
end;
$$;

revoke all on function public.create_business_story(
  uuid, text, text, text, text, text, text, text, timestamptz
) from public;
grant execute on function public.create_business_story(
  uuid, text, text, text, text, text, text, text, timestamptz
) to authenticated;

-- Limpieza horaria: la función elimina primero el archivo y luego el registro.
create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'tc-cleanup-expired-stories'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;

  perform cron.schedule(
    'tc-cleanup-expired-stories',
    '15 * * * *',
    $job$
      select net.http_post(
        url := 'https://czbukztebwrfpvbvycje.supabase.co/functions/v1/cleanup-stories',
        headers := '{"Content-Type":"application/json"}'::jsonb,
        body := '{"source":"cron"}'::jsonb
      );
    $job$
  );
end $$;
